### ISSUE TITLE
Audio Direct

### ISSUE THREAD

**Issue by dukeduke02** [featherbear/aNDI#6]
So I was looking for a way off decoding an NDI source into Android phones. We are getting ready for a big event, we have an intercon system that will not support every one and we need to cover 4 floors. Sice we have a really good network infraestructure I integrated our intercon system sending a signal to my behringer UMC 22 audio interface and creating an NDI output in my DAW with Audio Direct VST plugin. Now I need to decode the NDI signal on some old Android phones we have hangging around the office. This Android NDI suite can help me?

**Comment by featherbear** [comment]
Hi, I haven't looked into audio decoding on this project unfortunately, and won't be looking at it any time soon sorry!

For an Android device, sounds like you might want to look into some more WebRTC-based, or multicast-based audio broadcasts...

Or if you've got enough network capacity, then perhaps look at applications like AudioRelay or SoundWire rather than through NDI.

**Comment by dukeduke02** [comment]
Thanks for the reply!

**Comment by BrandonHortman** [comment]
> So I was looking for a way off decoding an NDI source into Android phones. We are getting ready for a big event, we have an intercon system that will not support every one and we need to cover 4 floors. Sice we have a really good network infraestructure I integrated our intercon system sending a signal to my behringer UMC 22 audio interface and creating an NDI output in my DAW with Audio Direct VST plugin. Now I need to decode the NDI signal on some old Android phones we have hangging around the office. This Android NDI suite can help me?

Duke use Sonobus. It runs on everything and can ship audio anywhere.

Our com matrix has a Dante card so I just simply use Dante via to route a com channel into it or discord

**Comment by dukeduke02** [comment]
@BrandonHortman thanks for the tip, it was much easier with sonobus!
